// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMZHcqPhwpQbmjVerR-qVPOif868EdRaI',
    appId: '1:27418955628:web:899af3c17c7f8c5c886d49',
    messagingSenderId: '27418955628',
    projectId: 'ref-application',
    authDomain: 'ref-application.firebaseapp.com',
    storageBucket: 'ref-application.appspot.com',
    measurementId: 'G-6VFPQHM32Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAONmZSyYpmKa9diK6YXRrFi4PEtPIbUxg',
    appId: '1:27418955628:android:01348e835b61b3e2886d49',
    messagingSenderId: '27418955628',
    projectId: 'ref-application',
    storageBucket: 'ref-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmuRYVmflDiWJC6KsW48EWqMIZS3Wkau4',
    appId: '1:27418955628:ios:0f4d74ab2470b5a0886d49',
    messagingSenderId: '27418955628',
    projectId: 'ref-application',
    storageBucket: 'ref-application.appspot.com',
    iosClientId: '27418955628-divgl7vf23pggjgkidg5gkieesq709lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmuRYVmflDiWJC6KsW48EWqMIZS3Wkau4',
    appId: '1:27418955628:ios:0f4d74ab2470b5a0886d49',
    messagingSenderId: '27418955628',
    projectId: 'ref-application',
    storageBucket: 'ref-application.appspot.com',
    iosClientId: '27418955628-divgl7vf23pggjgkidg5gkieesq709lb.apps.googleusercontent.com',
    iosBundleId: 'com.example.referralApp',
  );
}
